version: 0.2

phases:
  build:
    commands:
      - cd lambda-deploy
      - zip -r9 deployment_package.zip .
      - zip -g deployment_package.zip lambda_function.py
      - aws lambda update-function-code --function-name lambda-deploy --zip-file fileb://deployment_package.zip