version: 0.2

phases:
  build:
    commands:
      - cd lambda-deploy
      - zip -r9 deployment_package.zip .
      - aws lambda update-function-code --function-name lambda-deploy --zip-file fileb://deployment_package.zip
      - cd ../lambda-deploy-node
      - zip -r9 deployment_package.zip .
      - aws lambda update-function-code --function-name lambda-deploy-node --zip-file fileb://deployment_package.zip